# Generated by Django 4.2.13 on 2024-05-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Usuarios', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20, null=True)),
                ('num_celular', models.CharField(max_length=10, null=True)),
                ('num_cedula', models.CharField(max_length=10, null=True)),
                ('correo', models.CharField(max_length=30, null=True)),
                ('contra', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
