# Generated by Django 4.2.13 on 2024-05-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_usuario_rol_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Usuario', 'Usuario'), ('Analista', 'Analista'), ('Administrador', 'Administrador')], default='Usuario'),
        ),
    ]
