# Generated by Django 4.2.13 on 2024-05-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fijo_Suscriptores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('trimestre', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('id_segmento', models.IntegerField(null=True)),
                ('segmento', models.CharField(max_length=10, null=True)),
                ('id_empresa', models.IntegerField(null=True)),
                ('empresa', models.CharField(null=True)),
                ('id_terminal', models.IntegerField(null=True)),
                ('terminal', models.CharField(null=True)),
                ('id_tecnologia', models.IntegerField(null=True)),
                ('tecnologia', models.CharField(null=True)),
                ('cantidad_suscriptores', models.IntegerField(null=True)),
            ],
        ),
    ]
