# Generated by Django 4.2.13 on 2024-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_demanda_abonados_demanda_ingresos_demanda_trafico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fijo_ingresos',
            name='ingresos',
            field=models.BigIntegerField(null=True),
        ),
    ]
