# Generated by Django 4.2.13 on 2024-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_fijo_ingresos_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('colombia_telecomunicaciones', models.BigIntegerField(null=True)),
                ('colombia_movil', models.BigIntegerField(null=True)),
                ('comunicacion_celular_comcel', models.BigIntegerField(null=True)),
                ('empresa_de_telecomunicaciones_de_bogota', models.BigIntegerField(null=True)),
                ('une_epm', models.BigIntegerField(null=True)),
                ('avantel', models.BigIntegerField(null=True)),
                ('almacenes_exito', models.BigIntegerField(null=True)),
                ('virgin_mobile', models.BigIntegerField(null=True)),
                ('partners_telecom', models.BigIntegerField(null=True)),
                ('setroc_mobile', models.BigIntegerField(null=True)),
                ('uff_movil', models.BigIntegerField(null=True)),
                ('cellvoz_colombia', models.BigIntegerField(null=True)),
                ('logistica_flash', models.BigIntegerField(null=True)),
                ('lov_telecomunicaciones', models.BigIntegerField(null=True)),
                ('suma_movil', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Demanda_Abonados',
        ),
        migrations.DeleteModel(
            name='Demanda_Ingresos',
        ),
        migrations.DeleteModel(
            name='Demanda_Trafico',
        ),
        migrations.DeleteModel(
            name='Fijo_Ingresos',
        ),
        migrations.DeleteModel(
            name='Fijo_Suscriptores',
        ),
        migrations.DeleteModel(
            name='Fijo_Trafico',
        ),
    ]
