# Generated by Django 4.2.13 on 2024-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_abonados_delete_demanda_abonados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('colombia_telecomunicaciones', models.BigIntegerField(null=True)),
                ('colombia_movil', models.BigIntegerField(null=True)),
                ('comunicacion_celular_comcel', models.BigIntegerField(null=True)),
                ('empresa_de_telecomunicaciones_de_bogota', models.BigIntegerField(null=True)),
                ('une_epm', models.BigIntegerField(null=True)),
                ('avantel', models.BigIntegerField(null=True)),
                ('almacenes_exito', models.BigIntegerField(null=True)),
                ('virgin_mobile', models.BigIntegerField(null=True)),
                ('partners_telecom', models.BigIntegerField(null=True)),
                ('setroc_mobile', models.BigIntegerField(null=True)),
                ('uff_movil', models.BigIntegerField(null=True)),
                ('cellvoz_colombia', models.BigIntegerField(null=True)),
                ('logistica_flash', models.BigIntegerField(null=True)),
                ('lov_telecomunicaciones', models.BigIntegerField(null=True)),
                ('suma_movil', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trafico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('colombia_telecomunicaciones', models.BigIntegerField(null=True)),
                ('colombia_movil', models.BigIntegerField(null=True)),
                ('comunicacion_celular_comcel', models.BigIntegerField(null=True)),
                ('empresa_de_telecomunicaciones_de_bogota', models.BigIntegerField(null=True)),
                ('une_epm', models.BigIntegerField(null=True)),
                ('avantel', models.BigIntegerField(null=True)),
                ('almacenes_exito', models.BigIntegerField(null=True)),
                ('virgin_mobile', models.BigIntegerField(null=True)),
                ('partners_telecom', models.BigIntegerField(null=True)),
                ('setroc_mobile', models.BigIntegerField(null=True)),
                ('uff_movil', models.BigIntegerField(null=True)),
                ('cellvoz_colombia', models.BigIntegerField(null=True)),
                ('logistica_flash', models.BigIntegerField(null=True)),
                ('lov_telecomunicaciones', models.BigIntegerField(null=True)),
                ('suma_movil', models.BigIntegerField(null=True)),
            ],
        ),
    ]
