# Generated by Django 4.2.13 on 2024-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_ingresos_trafico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stenbaka_Abonados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('stenbaka', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stenbaka_Ingresos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('stenbaka', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stenbaka_Trafico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('stenbaka', models.IntegerField(null=True)),
            ],
        ),
    ]
